### ISSUE TITLE
Another issue (sorry!)

### ISSUE THREAD

**Issue by lriley2020** [TwoSails/WeatherDashboard#11]
I've been trying really hard to get this working for the past two days but still haven't had any luck. I think this is mainly becuase I don't really have any idea how to get the sensor data into the application, or how the application is meant to be configured. I am trying to use this software along with a temperature, pressure and humidity sensor to display information locally over my home network. The latest issue that I am hitting is when clicking the add city button, nothing happens. I have tried looking at the `weatherapp_city` table in `db.sqlite3`, but nothing is shown there. I understand that this is a personal project and not your priority, but I would be greatful if you could explian how I could get this working as this seems to be the best dashboard for my uses.

**Comment by TwoSails** [comment]
Hello, 
First, this was a project which I designed myself to work for the problem I have. I should make it clear in the documentation that the root directory, which are describing, is not the main project and was merely a test for me to see if all dependencies were installed correct and the site ran.

The project is based in the `/dashboard` directory. This page gathers data from a MongoDB database, as that was my database of choice. (The configuration should be able to be found on the admin page at `/admin`, This would require a SUPERUSER to be created as mentioned in the documentation).

This was designed around that single database, as I personally had no need to support others.
However, this can be easily implemented yourself, as all data collection is located in one function in the `./weatherapp/util/data.py` file. If you want to change the database, this would be your best bet.

From my understanding, you are trying to use your own sensor data instead of from an existing API?

Feel free to ask more questions, as I will leave this issue open.
Hope this helps

**Comment by lriley2020** [comment]
Thanks for helping with this, I really appreciate it! This is my first time even seeing a django application so apologies in advance for any lack of knowledge. Is there any way I could add my own data to the mongoDB database, in the same way it would be added if it came from an API?

**Comment by TwoSails** [comment]
Sorry, just wondering where is the data coming from?
Is it your own API? Another database?

**Comment by lriley2020** [comment]
I currently don't have any way of storing the data from my sensors, as this was my go-to solution. I'm hoping that I'll be able to insert the data my sensors recieve directly into the mongoDB database using a python script

**Comment by TwoSails** [comment]
Yes! This would be perfect. 
First, you will want to install the actual MongoDB database on to your sensor's device, which I am assuming is a Linux computer, most likely a Raspberry Pi (am I right?). If so, here is a great guide which I used to set it up myself: https://developer.mongodb.com/how-to/mongodb-on-raspberry-pi/ 

The thing about MongoDB is that it is a document based database, meaning it stores data as JSON documents.
Here is some simple code which would input the data into the database, similar to how I implemented it.
```py
import time
import pymongo
from pymongo import MongoClient

cluster = MongoClient('localhost', 27017, connect=False)
db = cluster['weather']
collection = db['weatherCollection']

data = {'temperature': 27.8,
        'pressure': 1076,
        'humidity': 47,
'TIMESTAMP': time.time()}

collection.insert_one(data)
```

This would then work well with the dashboard, as the config would only slightly be changed:

```yaml
mongoDBString: YOUR DATABASE STRING
    mongoDB:
      windDirection: windAverage
      recentSpeed: recentSpeed
      avgWindSpeed: windSpeedAverage
      windGust: windGust
      rainfall: rainfall
      humidity: humidity
      pressure: pressure
      ambientTemp: temperature
      groundTemp: groundTemp

...

sensors:
    windDirection: false
    windSpeed: false
    rainfall: false
    humidity: true
    pressure: true
    ambientTemp: true
    groundTemp: false
```
I just did a patch, which should mean that you don't have to worry about adding unnecessary fields into your database

Don't hesitate to ask any more questions...

**Comment by lriley2020** [comment]
Thanks so much for this - I've never had this much support from someone regarding a computer project before so thanks! I'll start installing ubuntu server now and get back to you with the results!

**Comment by TwoSails** [comment]
Yeah no problem, I want to make sure people enjoy programming and not many people have used my code before, so thank you...

Good luck

**Comment by lriley2020** [comment]
Actually, do you think there will be any adverse affects if I keep my raspbian installation and use an older version of mongoDB? Just asking becuase I'm slightly worried I'll lose some functionality with the physical hardware of my raspberry pi (eg: i2c interface for my sensor) if I use Ubuntu server instead.

**Comment by TwoSails** [comment]
I don't see an issue with that, I currently use Raspberry Pi OS for my weather station, just use an older version, and it should work.
And also use `pymongo==3.4.0` as that will work for the outdated MongoDB version.

**Comment by lriley2020** [comment]
Great, thanks!

**Comment by lriley2020** [comment]
I have installed the database on my raspberry pi but I now get the following message when launching the dashboard
```
OperationFailure at /dashboard/
database error: not authorized for query on weather.weatherCollection

```
I was expecting this to happen as I haven't made any databases or users yet but I don't really know how best to set up the database for the dashboard. What should I name the database and collections for them to work with the dashboard?

**Comment by TwoSails** [comment]
For it to work with the dashboard, set your database name to: `weather` and the collection to `weatherCollection` and then it should work.

**Comment by lriley2020** [comment]
Hi, I'm now getting a `key errror` when I try to access the dashboard. Is the django secret key (I haven't put a vaule for this yet) something to do with this?

**Comment by TwoSails** [comment]
Can I look at the full error please?

**Comment by lriley2020** [comment]
Certainly, just give me a few minuted to recreate it :)

**Comment by lriley2020** [comment]
From server side:
```
Traceback (most recent call last):
  File "/home/pi/weatherenv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/pi/weatherenv/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/pi/weatherenv/lib/python3.7/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/pi/WeatherDashboard/weatherapp/views.py", line 38, in dashboard
    data.all_data()
  File "/home/pi/WeatherDashboard/weatherapp/util/data.py", line 38, in all_data
    sensors = self.config['dashboard']['sensors']
KeyError: 'dashboard'
```

**Comment by TwoSails** [comment]
Could you also send the config file too?
sorry

**Comment by lriley2020** [comment]
Np, here it is:
```
dashboard:
  quickLook:
    format:
      windDirection: txt
    periods:
      ambientTemp: 30
      avgWindSpeed: 360
      groundTemp: 30
      humidity: 30
      pressure: 30
      rainfall: 720
      windDirection: 30
      windGust: 720
  sensors:
    ambientTemp: true
    groundTemp: false
    humidity: true
    pressure: true
    rainfall: true
    windDirection: true
    windSpeed: true
  settings:
    SECRET_KEY: YOUR SECRET KEY
    mongoDB:
      ambientTemp: ambientTemp
      avgWindSpeed: windSpeedAverage
      groundTemp: groundTemp
      humidity: humidity
      pressure: pressure
      rainfall: rainfall
      recentSpeed: recentSpeed
      windDirection: windAverage
      windGust: windGust
    mongoDBString: raspberrypizero.local
    units:
      input:
        rainfall: mm
        speed: km/h
        temp: celsius
      output:
        rainfall: mm
        speed: km/h
        temp: celsius
```

**Comment by lriley2020** [comment]
(I wasn't sure what to fill in for the SECRET_KEY)

**Comment by TwoSails** [comment]
Ahh right, your config is fine, it is my code which I quickly and poorly wrote...
I made a patch but to save you updating your code, here is what it is meant to look like on line 38 in `./weatherapp/util/data`
https://github.com/TwoSails/WeatherDashboard/blob/753f64664d0608b17b83094b2e4294d32f27fe5d/weatherapp/util/data.py#L38 

You should be able to just delete `["dashboard"]`. Sorry about that

**Comment by lriley2020** [comment]
No problem, thanks a lot for spending so much time on this!

**Comment by lriley2020** [comment]
I'll try that now

**Comment by lriley2020** [comment]
No cigar :(
It's now showing an error about the wind speed:
```
Traceback (most recent call last):
  File "/home/pi/weatherenv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/pi/weatherenv/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/pi/weatherenv/lib/python3.7/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/pi/WeatherDashboard/weatherapp/views.py", line 38, in dashboard
    data.all_data()
  File "/home/pi/WeatherDashboard/weatherapp/util/data.py", line 41, in all_data
    self.data['windDirection'].append(x[self.endpoints['windDirection']])
KeyError: 'windAverage'
```

**Comment by lriley2020** [comment]
Is this the same error but with a different variable?

**Comment by TwoSails** [comment]
Do you have Wind Speed and Wind Direction sensors/data in your MongoDB database?
If not, then you will have to change part of your config to this:
```YAML
sensors:
    ambientTemp: true
    groundTemp: false
    humidity: true
    pressure: true
    rainfall: false
    windDirection: false
    windSpeed: false
```
